In [1]:
import numpy as np
import torch

%reload_ext nb_black

<IPython.core.display.Javascript object>

In [2]:
tensor = torch.rand(4, 3)
tensor

tensor([[0.3343, 0.7636, 0.5226],
        [0.9031, 0.2444, 0.0457],
        [0.2593, 0.1696, 0.0122],
        [0.6016, 0.1690, 0.7678]])

<IPython.core.display.Javascript object>

In [3]:
type(tensor)

torch.Tensor

<IPython.core.display.Javascript object>

In [4]:
numpy_from_tensor = tensor.numpy()
numpy_from_tensor

array([[0.33434236, 0.7635923 , 0.5225597 ],
       [0.9031114 , 0.24441177, 0.0457359 ],
       [0.2592547 , 0.16963047, 0.01219416],
       [0.6015779 , 0.16895062, 0.76778674]], dtype=float32)

<IPython.core.display.Javascript object>

In [5]:
type(numpy_from_tensor)

numpy.ndarray

<IPython.core.display.Javascript object>

In [6]:
torch.is_tensor(tensor)

True

<IPython.core.display.Javascript object>

In [7]:
torch.is_tensor(numpy_from_tensor)

False

<IPython.core.display.Javascript object>

In [8]:
# the numpy array and the pytorch tensor share the same underlying memory
numpy_from_tensor[0, 0] = 100.0
numpy_from_tensor

array([[1.0000000e+02, 7.6359230e-01, 5.2255970e-01],
       [9.0311140e-01, 2.4441177e-01, 4.5735896e-02],
       [2.5925469e-01, 1.6963047e-01, 1.2194157e-02],
       [6.0157788e-01, 1.6895062e-01, 7.6778674e-01]], dtype=float32)

<IPython.core.display.Javascript object>

In [9]:
tensor

tensor([[1.0000e+02, 7.6359e-01, 5.2256e-01],
        [9.0311e-01, 2.4441e-01, 4.5736e-02],
        [2.5925e-01, 1.6963e-01, 1.2194e-02],
        [6.0158e-01, 1.6895e-01, 7.6779e-01]])

<IPython.core.display.Javascript object>

In [10]:
numpy_arr = np.array([[1.0, 2.0, 3.0], [10.0, 20.0, 30.0], [100.0, 200.0, 300.0]])
numpy_arr

array([[  1.,   2.,   3.],
       [ 10.,  20.,  30.],
       [100., 200., 300.]])

<IPython.core.display.Javascript object>

In [11]:
tensor_from_numpy = torch.from_numpy(numpy_arr)
tensor_from_numpy

tensor([[  1.,   2.,   3.],
        [ 10.,  20.,  30.],
        [100., 200., 300.]], dtype=torch.float64)

<IPython.core.display.Javascript object>

In [12]:
type(tensor_from_numpy)

torch.Tensor

<IPython.core.display.Javascript object>

In [13]:
torch.is_tensor(tensor_from_numpy)

True

<IPython.core.display.Javascript object>

In [14]:
tensor_from_numpy[0] = 1
tensor_from_numpy

tensor([[  1.,   1.,   1.],
        [ 10.,  20.,  30.],
        [100., 200., 300.]], dtype=torch.float64)

<IPython.core.display.Javascript object>

In [15]:
numpy_arr

array([[  1.,   1.,   1.],
       [ 10.,  20.,  30.],
       [100., 200., 300.]])

<IPython.core.display.Javascript object>

In [16]:
np_array_one = np.array([4, 8])
np_array_one

array([4, 8])

<IPython.core.display.Javascript object>

In [17]:
# performs a copy if the data is not already a tensor - here since we are not changing the data type or device (CPU/GPU), the new tensor will just use the same memory

# if the data is already a tensor with the same dtype and device, then no copy is performed and the new tensor is returned with the same computational graph

tensor_from_array_one = torch.as_tensor(np_array_one)
tensor_from_array_one

tensor([4, 8], dtype=torch.int32)

<IPython.core.display.Javascript object>

In [18]:
np_array_one[1] = 5
np_array_one

array([4, 5])

<IPython.core.display.Javascript object>

In [19]:
tensor_from_array_one

tensor([4, 5], dtype=torch.int32)

<IPython.core.display.Javascript object>

In [20]:
np_array_two = np.array([2, 2])
np_array_two

array([2, 2])

<IPython.core.display.Javascript object>

In [21]:
tensor_from_array_two = torch.tensor(np_array_two)
tensor_from_array_two

tensor([2, 2], dtype=torch.int32)

<IPython.core.display.Javascript object>

In [22]:
np_array_two[1] = 4
np_array_two

array([2, 4])

<IPython.core.display.Javascript object>

In [23]:
tensor_from_array_two

tensor([2, 2], dtype=torch.int32)

<IPython.core.display.Javascript object>