In [1]:
import numpy as np
import torch
import torch.nn as nn

In [2]:
W = torch.randn(6)
x = torch.tensor([10.0, 10.0, 10.0, 10.0, 10.0, 10.0])
b = torch.tensor(3)

In [3]:
W

tensor([ 2.0920, -0.1484, -0.1798, -0.1728, -0.0897, -0.2095])

In [4]:
y = W * x + b

In [5]:
y

tensor([23.9197,  1.5162,  1.2023,  1.2715,  2.1033,  0.9054])

In [6]:
W * x

tensor([20.9197, -1.4838, -1.7977, -1.7285, -0.8967, -2.0946])

In [7]:
b

tensor(3)

In [8]:
W1 = torch.tensor(6)
W2 = torch.tensor(6)
W3 = torch.tensor(6)

x1 = torch.tensor([2, 2, 2])
x2 = torch.tensor([3, 3, 3])
x3 = torch.tensor([4, 4, 4])

b = torch.tensor(10)

In [9]:
W1, W2, W3

(tensor(6), tensor(6), tensor(6))

In [10]:
intermediate_value = W1 * x1 + W2 * x2
intermediate_value

tensor([30, 30, 30])

In [11]:
final_value = W1 * x1 + W2 * x2 + W3 * x3 + b
final_value

tensor([64, 64, 64])

In [12]:
import hiddenlayer as hl

In [13]:
x_train = np.array(
    [[1.7], [2.5], [5.5], [7.9], [8.8], [2.4], [2.4], [8.89], [5], [4.4]],
    dtype=np.float32)

y_train = np.array(
    [[1.9], [2.68], [4.22], [8.19], [9.69], [3.4], [2.6], [8.8], [5.6], [4.7]],
    dtype=np.float32)

In [14]:
X_train = torch.tensor(x_train)
Y_train = torch.tensor(y_train)
X_train.shape

torch.Size([10, 1])

In [15]:
inp = 1
out = 1

hid = 100

In [16]:
model1 = torch.nn.Sequential(torch.nn.Linear(
    inp, hid), torch.nn.Linear(hid, out))

In [17]:
hl.build_graph(model1, torch.zeros([10, 1]))

TypeError: _jit_pass_onnx_unpack_quantized_weights(): incompatible function arguments. The following argument types are supported:
    1. (arg0: torch::jit::Graph, arg1: Dict[str, IValue], arg2: bool) -> Dict[str, IValue]

Invoked with: graph(%0 : Float(10, 1, strides=[1, 1], requires_grad=0, device=cpu),
      %1 : Float(100, 1, strides=[1, 1], requires_grad=1, device=cpu),
      %2 : Float(100, strides=[1], requires_grad=1, device=cpu),
      %3 : Float(1, 100, strides=[100, 1], requires_grad=1, device=cpu),
      %4 : Float(1, strides=[1], requires_grad=1, device=cpu)):
  %15 : Float(10, 100, strides=[100, 1], requires_grad=1, device=cpu) = aten::linear(%0, %1, %2) # C:\Users\natha\AppData\Roaming\Python\Python310\site-packages\torch\nn\modules\linear.py:114:0
  %16 : Float(10, 1, strides=[1, 1], requires_grad=1, device=cpu) = aten::linear(%15, %3, %4) # C:\Users\natha\AppData\Roaming\Python\Python310\site-packages\torch\nn\modules\linear.py:114:0
  return (%16)
, None, False

In [18]:
hl.build_graph(model1, torch.zeros([1]))

TypeError: _jit_pass_onnx_unpack_quantized_weights(): incompatible function arguments. The following argument types are supported:
    1. (arg0: torch::jit::Graph, arg1: Dict[str, IValue], arg2: bool) -> Dict[str, IValue]

Invoked with: graph(%0 : Float(1, strides=[1], requires_grad=0, device=cpu),
      %1 : Float(100, 1, strides=[1, 1], requires_grad=1, device=cpu),
      %2 : Float(100, strides=[1], requires_grad=1, device=cpu),
      %3 : Float(1, 100, strides=[100, 1], requires_grad=1, device=cpu),
      %4 : Float(1, strides=[1], requires_grad=1, device=cpu)):
  %15 : Float(100, strides=[1], requires_grad=1, device=cpu) = aten::linear(%0, %1, %2) # C:\Users\natha\AppData\Roaming\Python\Python310\site-packages\torch\nn\modules\linear.py:114:0
  %16 : Float(1, strides=[1], requires_grad=1, device=cpu) = aten::linear(%15, %3, %4) # C:\Users\natha\AppData\Roaming\Python\Python310\site-packages\torch\nn\modules\linear.py:114:0
  return (%16)
, None, False

In [19]:
model2 = torch.nn.Sequential(torch.nn.Linear(inp, hid),
                             torch.nn.Linear(hid, hid),
                             torch.nn.Sigmoid(),
                             torch.nn.Linear(hid, out))

In [20]:
hl.build_graph(model2, torch.zeros([10, 1]))

TypeError: _jit_pass_onnx_unpack_quantized_weights(): incompatible function arguments. The following argument types are supported:
    1. (arg0: torch::jit::Graph, arg1: Dict[str, IValue], arg2: bool) -> Dict[str, IValue]

Invoked with: graph(%0 : Float(10, 1, strides=[1, 1], requires_grad=0, device=cpu),
      %1 : Float(100, 1, strides=[1, 1], requires_grad=1, device=cpu),
      %2 : Float(100, strides=[1], requires_grad=1, device=cpu),
      %3 : Float(100, 100, strides=[100, 1], requires_grad=1, device=cpu),
      %4 : Float(100, strides=[1], requires_grad=1, device=cpu),
      %5 : Float(1, 100, strides=[100, 1], requires_grad=1, device=cpu),
      %6 : Float(1, strides=[1], requires_grad=1, device=cpu)):
  %21 : Float(10, 100, strides=[100, 1], requires_grad=1, device=cpu) = aten::linear(%0, %1, %2) # C:\Users\natha\AppData\Roaming\Python\Python310\site-packages\torch\nn\modules\linear.py:114:0
  %22 : Float(10, 100, strides=[100, 1], requires_grad=1, device=cpu) = aten::linear(%21, %3, %4) # C:\Users\natha\AppData\Roaming\Python\Python310\site-packages\torch\nn\modules\linear.py:114:0
  %23 : Float(10, 100, strides=[100, 1], requires_grad=1, device=cpu) = aten::sigmoid(%22) # C:\Users\natha\AppData\Roaming\Python\Python310\site-packages\torch\nn\modules\activation.py:290:0
  %24 : Float(10, 1, strides=[1, 1], requires_grad=1, device=cpu) = aten::linear(%23, %5, %6) # C:\Users\natha\AppData\Roaming\Python\Python310\site-packages\torch\nn\modules\linear.py:114:0
  return (%24)
, None, False

In [21]:
hl.build_graph(model2, torch.zeros([1]))

TypeError: _jit_pass_onnx_unpack_quantized_weights(): incompatible function arguments. The following argument types are supported:
    1. (arg0: torch::jit::Graph, arg1: Dict[str, IValue], arg2: bool) -> Dict[str, IValue]

Invoked with: graph(%0 : Float(1, strides=[1], requires_grad=0, device=cpu),
      %1 : Float(100, 1, strides=[1, 1], requires_grad=1, device=cpu),
      %2 : Float(100, strides=[1], requires_grad=1, device=cpu),
      %3 : Float(100, 100, strides=[100, 1], requires_grad=1, device=cpu),
      %4 : Float(100, strides=[1], requires_grad=1, device=cpu),
      %5 : Float(1, 100, strides=[100, 1], requires_grad=1, device=cpu),
      %6 : Float(1, strides=[1], requires_grad=1, device=cpu)):
  %21 : Float(100, strides=[1], requires_grad=1, device=cpu) = aten::linear(%0, %1, %2) # C:\Users\natha\AppData\Roaming\Python\Python310\site-packages\torch\nn\modules\linear.py:114:0
  %22 : Float(100, strides=[1], requires_grad=1, device=cpu) = aten::linear(%21, %3, %4) # C:\Users\natha\AppData\Roaming\Python\Python310\site-packages\torch\nn\modules\linear.py:114:0
  %23 : Float(100, strides=[1], requires_grad=1, device=cpu) = aten::sigmoid(%22) # C:\Users\natha\AppData\Roaming\Python\Python310\site-packages\torch\nn\modules\activation.py:290:0
  %24 : Float(1, strides=[1], requires_grad=1, device=cpu) = aten::linear(%23, %5, %6) # C:\Users\natha\AppData\Roaming\Python\Python310\site-packages\torch\nn\modules\linear.py:114:0
  return (%24)
, None, False