In [1]:
import torch

%reload_ext nb_black

<IPython.core.display.Javascript object>

In [2]:
torch.get_default_dtype()

torch.float32

<IPython.core.display.Javascript object>

In [3]:
torch.set_default_dtype(torch.float64)

<IPython.core.display.Javascript object>

In [4]:
tensor_arr = torch.Tensor([[1, 2, 3], [4, 5, 6]])
tensor_arr

tensor([[1., 2., 3.],
        [4., 5., 6.]])

<IPython.core.display.Javascript object>

In [5]:
# check if type tensor
torch.is_tensor(tensor_arr)

True

<IPython.core.display.Javascript object>

In [6]:
# print number of elements in tensor
torch.numel(tensor_arr)

6

<IPython.core.display.Javascript object>

In [7]:
# when specify torch.tensor and only indicate shape of tensor it will be uninitialized
tensor_uninitialized = torch.Tensor(2, 2)

# thus pytorch will allocate memory for this tensor but won't set up inital values
tensor_uninitialized

tensor([[8.7581e+189, 2.2506e-153],
        [ 6.7006e+91, 4.2724e+180]])

<IPython.core.display.Javascript object>

In [8]:
# create initialized tensor and fill with random values
tensor_initialized = torch.rand(2, 2)
tensor_initialized

# quick and easy way to initialize weights of model params

tensor([[0.6995, 0.2135],
        [0.5552, 0.1772]])

<IPython.core.display.Javascript object>

In [9]:
# to not use the default tensor dtype
tensor_int = torch.tensor([5, 3]).type(torch.IntTensor)
tensor_int

tensor([5, 3], dtype=torch.int32)

<IPython.core.display.Javascript object>

In [10]:
tensor_short = torch.ShortTensor([1, 2, 3])
tensor_short

tensor([1, 2, 3], dtype=torch.int16)

<IPython.core.display.Javascript object>

In [11]:
tensor_float = torch.tensor([1.0, 2.0, 3.0]).type(torch.half)
tensor_float

tensor([1., 2., 3.], dtype=torch.float16)

<IPython.core.display.Javascript object>

In [12]:
tensor_fill = torch.full((2, 6), fill_value=10)
tensor_fill

tensor([[10, 10, 10, 10, 10, 10],
        [10, 10, 10, 10, 10, 10]])

<IPython.core.display.Javascript object>

In [13]:
tensor_of_ones = torch.ones([2, 4], dtype=torch.int32)
tensor_of_ones

tensor([[1, 1, 1, 1],
        [1, 1, 1, 1]], dtype=torch.int32)

<IPython.core.display.Javascript object>

In [14]:
tensor_of_zeros = torch.zeros_like(tensor_of_ones)
tensor_of_zeros

tensor([[0, 0, 0, 0],
        [0, 0, 0, 0]], dtype=torch.int32)

<IPython.core.display.Javascript object>

In [15]:
torch_eye = torch.eye(5)
torch_eye

tensor([[1., 0., 0., 0., 0.],
        [0., 1., 0., 0., 0.],
        [0., 0., 1., 0., 0.],
        [0., 0., 0., 1., 0.],
        [0., 0., 0., 0., 1.]])

<IPython.core.display.Javascript object>

In [16]:
non_zero = torch.nonzero(torch_eye)
non_zero

tensor([[0, 0],
        [1, 1],
        [2, 2],
        [3, 3],
        [4, 4]])

<IPython.core.display.Javascript object>

In [17]:
i = torch.tensor([[0, 1, 1], [2, 2, 0]])

<IPython.core.display.Javascript object>

In [18]:
v = torch.tensor([3, 4, 5], dtype=torch.float32)

<IPython.core.display.Javascript object>

In [19]:
sparse_tensor = torch.sparse_coo_tensor(i, v, [2, 5])
sparse_tensor.data

tensor(indices=tensor([[0, 1, 1],
                       [2, 2, 0]]),
       values=tensor([3., 4., 5.]),
       size=(2, 5), nnz=3, dtype=torch.float32, layout=torch.sparse_coo)

<IPython.core.display.Javascript object>

In [20]:
initial_tensor = torch.rand(2, 3)
initial_tensor

tensor([[0.4248, 0.8899, 0.3398],
        [0.5705, 0.6378, 0.0839]])

<IPython.core.display.Javascript object>

In [21]:
initial_tensor.fill_(10)

tensor([[10., 10., 10.],
        [10., 10., 10.]])

<IPython.core.display.Javascript object>

In [22]:
new_tensor = initial_tensor.add(5)
new_tensor

tensor([[15., 15., 15.],
        [15., 15., 15.]])

<IPython.core.display.Javascript object>

In [23]:
initial_tensor.add_(8)
initial_tensor

tensor([[18., 18., 18.],
        [18., 18., 18.]])

<IPython.core.display.Javascript object>

In [24]:
new_tensor.sqrt_()
new_tensor

tensor([[3.8730, 3.8730, 3.8730],
        [3.8730, 3.8730, 3.8730]])

<IPython.core.display.Javascript object>

In [25]:
x = torch.linspace(start=0.1, end=10.0, steps=15)
x

tensor([ 0.1000,  0.8071,  1.5143,  2.2214,  2.9286,  3.6357,  4.3429,  5.0500,
         5.7571,  6.4643,  7.1714,  7.8786,  8.5857,  9.2929, 10.0000])

<IPython.core.display.Javascript object>

In [26]:
tensor_chunk = torch.chunk(x, 3, 0)
tensor_chunk

(tensor([0.1000, 0.8071, 1.5143, 2.2214, 2.9286]),
 tensor([3.6357, 4.3429, 5.0500, 5.7571, 6.4643]),
 tensor([ 7.1714,  7.8786,  8.5857,  9.2929, 10.0000]))

<IPython.core.display.Javascript object>

In [27]:
tensor1 = tensor_chunk[0]
tensor2 = tensor_chunk[1]
tensor3 = torch.tensor([3.0, 4.0, 5.0])

torch.cat((tensor1, tensor2, tensor3), 0)

tensor([0.1000, 0.8071, 1.5143, 2.2214, 2.9286, 3.6357, 4.3429, 5.0500, 5.7571,
        6.4643, 3.0000, 4.0000, 5.0000])

<IPython.core.display.Javascript object>

In [28]:
random_tensor = torch.Tensor([[10, 8, 30], [40, 5, 6], [12, 2, 21]])
random_tensor

tensor([[10.,  8., 30.],
        [40.,  5.,  6.],
        [12.,  2., 21.]])

<IPython.core.display.Javascript object>

In [29]:
random_tensor[0, 1]

tensor(8.)

<IPython.core.display.Javascript object>

In [30]:
random_tensor[1:, 1:]

tensor([[ 5.,  6.],
        [ 2., 21.]])

<IPython.core.display.Javascript object>

In [31]:
random_tensor.size()

torch.Size([3, 3])

<IPython.core.display.Javascript object>

In [32]:
resized_tensor = random_tensor.view(9)
resized_tensor

tensor([10.,  8., 30., 40.,  5.,  6., 12.,  2., 21.])

<IPython.core.display.Javascript object>

In [33]:
resized_tensor.size()

torch.Size([9])

<IPython.core.display.Javascript object>

In [34]:
random_tensor[2, 2] = 100.0
resized_tensor

tensor([ 10.,   8.,  30.,  40.,   5.,   6.,  12.,   2., 100.])

<IPython.core.display.Javascript object>

In [35]:
random_tensor

tensor([[ 10.,   8.,  30.],
        [ 40.,   5.,   6.],
        [ 12.,   2., 100.]])

<IPython.core.display.Javascript object>

In [36]:
random_tensor.shape

torch.Size([3, 3])

<IPython.core.display.Javascript object>

In [37]:
tensor_unsqueeze = torch.unsqueeze(random_tensor, 2)
tensor_unsqueeze

tensor([[[ 10.],
         [  8.],
         [ 30.]],

        [[ 40.],
         [  5.],
         [  6.]],

        [[ 12.],
         [  2.],
         [100.]]])

<IPython.core.display.Javascript object>

In [38]:
tensor_unsqueeze.shape

torch.Size([3, 3, 1])

<IPython.core.display.Javascript object>

In [39]:
tensor_transpose = torch.transpose(initial_tensor, 0, 1)
tensor_transpose

tensor([[18., 18.],
        [18., 18.],
        [18., 18.]])

<IPython.core.display.Javascript object>

In [40]:
sorted_tensor, sorted_indicies = torch.sort(random_tensor)

<IPython.core.display.Javascript object>

In [41]:
sorted_tensor

tensor([[  8.,  10.,  30.],
        [  5.,   6.,  40.],
        [  2.,  12., 100.]])

<IPython.core.display.Javascript object>

In [42]:
sorted_indicies

tensor([[1, 0, 2],
        [1, 2, 0],
        [1, 0, 2]])

<IPython.core.display.Javascript object>

In [43]:
tensor_float = torch.FloatTensor([-1.1, -2.2, 3.3])
tensor_float

tensor([-1.1000, -2.2000,  3.3000], dtype=torch.float32)

<IPython.core.display.Javascript object>

In [44]:
tensor_abs = torch.abs(tensor_float)
tensor_abs

tensor([1.1000, 2.2000, 3.3000], dtype=torch.float32)

<IPython.core.display.Javascript object>

In [45]:
rand1 = torch.abs(torch.randn(2, 3))
rand2 = torch.abs(torch.randn(2, 3))

<IPython.core.display.Javascript object>

In [46]:
add1 = rand1 + rand2
add1

tensor([[1.2818, 2.3013, 1.7597],
        [2.6891, 0.4932, 2.2761]])

<IPython.core.display.Javascript object>

In [47]:
add2 = torch.add(rand1, rand2)
add2

tensor([[1.2818, 2.3013, 1.7597],
        [2.6891, 0.4932, 2.2761]])

<IPython.core.display.Javascript object>

In [48]:
tensor = torch.Tensor([[-1, -2, -3], [1, 2, 3]])

<IPython.core.display.Javascript object>

In [49]:
tensor_div = torch.div(tensor, tensor + 0.3)
tensor_div

tensor([[1.4286, 1.1765, 1.1111],
        [0.7692, 0.8696, 0.9091]])

<IPython.core.display.Javascript object>

In [50]:
tensor_mul = torch.mul(tensor, tensor)
tensor_mul

tensor([[1., 4., 9.],
        [1., 4., 9.]])

<IPython.core.display.Javascript object>

In [51]:
tensor_clamp = torch.clamp(tensor, min=-0.2, max=2)
tensor_clamp

tensor([[-0.2000, -0.2000, -0.2000],
        [ 1.0000,  2.0000,  2.0000]])

<IPython.core.display.Javascript object>

In [52]:
t1 = torch.Tensor([1, 2])
t2 = torch.Tensor([10, 20])

<IPython.core.display.Javascript object>

In [53]:
dot_product = torch.dot(t1, t2)
dot_product

tensor(50.)

<IPython.core.display.Javascript object>

In [54]:
matrix = torch.Tensor([[1, 2, 3], [4, 5, 6]])

vector = torch.Tensor([0, 1, 2])

<IPython.core.display.Javascript object>

In [55]:
matrix_vector = torch.mv(matrix, vector)
matrix_vector

tensor([ 8., 17.])

<IPython.core.display.Javascript object>

In [56]:
another_matrix = torch.Tensor([[10, 20], [20, 0], [0, 50]])

<IPython.core.display.Javascript object>

In [57]:
matrix_mul = torch.mm(matrix, another_matrix)
matrix_mul

tensor([[ 50., 170.],
        [140., 380.]])

<IPython.core.display.Javascript object>

In [58]:
torch.argmax(matrix_mul, dim=1)

tensor([1, 1])

<IPython.core.display.Javascript object>

In [59]:
torch.argmin(matrix_mul, dim=1)

tensor([0, 0])

<IPython.core.display.Javascript object>