In [1]:
import numpy as np
import tensorflow as tf

In [2]:
tf.executing_eagerly()

True

In [5]:
W = tf.Variable(6, name="var_W")
x = tf.constant([10, 10], name="x")
b = tf.constant(3, name="constant_b")

In [6]:
W

<tf.Variable 'var_W:0' shape=() dtype=int32, numpy=6>

In [7]:
x

<tf.Tensor: shape=(2,), dtype=int32, numpy=array([10, 10])>

In [8]:
b

<tf.Tensor: shape=(), dtype=int32, numpy=3>

In [9]:
y = W * x + b

In [10]:
y

<tf.Tensor: shape=(2,), dtype=int32, numpy=array([63, 63])>

In [11]:
print(y)

tf.Tensor([63 63], shape=(2,), dtype=int32)


In [12]:
print(W * x)

tf.Tensor([60 60], shape=(2,), dtype=int32)


In [13]:
np_result = np.multiply(W, x)
np_result

array([60, 60])

In [14]:
W.numpy()

6

In [15]:
y.numpy()

array([63, 63])