In [11]:
import torch

import warnings

warnings.simplefilter("ignore", UserWarning)

In [12]:
tensor = torch.Tensor([[3, 4], [7, 5]])
tensor

tensor([[3., 4.],
        [7., 5.]])

In [13]:
tensor.requires_grad

False

In [14]:
tensor.requires_grad_()

tensor([[3., 4.],
        [7., 5.]], requires_grad=True)

In [15]:
print(tensor.grad)

None


In [16]:
print(tensor.grad_fn)

None


In [17]:
out = tensor * tensor
out.requires_grad

True

In [18]:
print(out.grad)

None


In [19]:
print(out.grad_fn)

In [20]:
out = (tensor * tensor).mean()
print(out.grad_fn)

In [21]:
print(tensor.grad)

None


In [22]:
out.backward()

In [23]:
print(tensor.grad)

tensor([[1.5000, 2.0000],
        [3.5000, 2.5000]])


In [24]:
new_tensor = tensor * tensor
print(new_tensor.requires_grad)

True


In [26]:
with torch.no_grad():
    new_tensor = tensor * tensor
    print("new_tensor = ", new_tensor)
    print("requires_grad for tensor = ", tensor.requires_grad)
    print("requires_grad for new_tensor = ", new_tensor.requires_grad)

new_tensor =  tensor([[ 9., 16.],
        [49., 25.]])
requires_grad for tensor =  True
requires_grad for new_tensor =  False
