In [1]:
import torch

In [2]:
tensor_array = torch.Tensor([[1, 2], [4, 5]])
tensor_array


tensor([[1., 2.],
        [4., 5.]])

In [3]:
tensor_uninitialized = torch.Tensor(3, 3)

In [4]:
torch.numel(tensor_uninitialized)

9

In [5]:
tensor_uninitialized

tensor([[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]])

In [6]:
tensor_initialized = torch.rand(2, 3)
tensor_initialized

tensor([[0.2192, 0.6986, 0.3534],
        [0.2905, 0.1937, 0.3300]])

In [7]:
tensor_int = torch.randn(5, 3).type(torch.IntTensor)
tensor_int

tensor([[ 0,  0,  1],
        [ 0,  2,  0],
        [ 0,  0,  0],
        [ 0,  1,  0],
        [-1,  0,  1]], dtype=torch.int32)

In [8]:
# tensor_long = torch.LongTensor([1.0, 2.0, 3.0])
# tensor_long


In [9]:
tensor_byte = torch.ByteTensor([0, 261, 1, -5])
tensor_byte

tensor([  0,   5,   1, 251], dtype=torch.uint8)

In [10]:
tensor_ones = torch.ones(10)
tensor_ones

tensor([1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

In [11]:
tensor_zeros = torch.zeros(10)
tensor_zeros

tensor([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [12]:
tensor_eye = torch.eye(3)
tensor_eye

tensor([[1., 0., 0.],
        [0., 1., 0.],
        [0., 0., 1.]])

In [13]:
non_zero = torch.nonzero(tensor_eye)
non_zero

tensor([[0, 0],
        [1, 1],
        [2, 2]])

In [14]:
tensor_ones_shape_eye = torch.ones_like(tensor_eye)
tensor_ones_shape_eye


tensor([[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]])

In [15]:
initial_tensor = torch.rand(3, 3)
initial_tensor.fill_(3)

tensor([[3., 3., 3.],
        [3., 3., 3.],
        [3., 3., 3.]])

In [16]:
# initial_tensor.fill(3)


In [17]:
new_tensor = initial_tensor.add(4)
new_tensor

tensor([[7., 7., 7.],
        [7., 7., 7.],
        [7., 7., 7.]])

In [18]:
initial_tensor

tensor([[3., 3., 3.],
        [3., 3., 3.],
        [3., 3., 3.]])

In [19]:
initial_tensor.add_(5)
initial_tensor

tensor([[8., 8., 8.],
        [8., 8., 8.],
        [8., 8., 8.]])

In [20]:
new_tensor

tensor([[7., 7., 7.],
        [7., 7., 7.],
        [7., 7., 7.]])

In [21]:
import numpy as np

In [22]:
numpy_arr = np.array([1, 2, 3])
numpy_arr

array([1, 2, 3])

In [23]:
tensor = torch.from_numpy(numpy_arr)
tensor

tensor([1, 2, 3], dtype=torch.int32)

In [24]:
numpy_from_tensor = tensor.numpy()
numpy_from_tensor

array([1, 2, 3])

In [25]:
numpy_arr[1] = 4
numpy_arr

array([1, 4, 3])

In [26]:
tensor

tensor([1, 4, 3], dtype=torch.int32)

In [27]:
numpy_from_tensor

array([1, 4, 3])

In [28]:
initial_tensor = torch.rand(2, 3)
initial_tensor

tensor([[0.9763, 0.4889, 0.9430],
        [0.1871, 0.4887, 0.0179]])

In [29]:
initial_tensor[0, 2]

tensor(0.9430)

In [30]:
initial_tensor[:, 1:]

tensor([[0.4889, 0.9430],
        [0.4887, 0.0179]])

In [31]:
initial_tensor.size()

torch.Size([2, 3])

In [32]:
initial_tensor.shape


torch.Size([2, 3])

In [33]:
resized_tensor = initial_tensor.view(6)
resized_tensor.shape


torch.Size([6])

In [34]:
resized_tensor

tensor([0.9763, 0.4889, 0.9430, 0.1871, 0.4887, 0.0179])

In [35]:
initial_tensor[0, 2] = 0.1111
resized_tensor

tensor([0.9763, 0.4889, 0.1111, 0.1871, 0.4887, 0.0179])

In [36]:
resized_tensor = initial_tensor.view(3, 2)
resized_tensor.shape

torch.Size([3, 2])

In [37]:
resized_tensor

tensor([[0.9763, 0.4889],
        [0.1111, 0.1871],
        [0.4887, 0.0179]])

In [38]:
resized_matrix = initial_tensor.view(-1, 2)
resized_matrix.shape

torch.Size([3, 2])

In [39]:
# resized_matrix = initial_tensor.view(-1, 5)


In [40]:
initial_tensor

tensor([[0.9763, 0.4889, 0.1111],
        [0.1871, 0.4887, 0.0179]])

In [41]:
sorted_tensor, sorted_indices = torch.sort(initial_tensor)

In [42]:
sorted_tensor

tensor([[0.1111, 0.4889, 0.9763],
        [0.0179, 0.1871, 0.4887]])

In [43]:
sorted_indices

tensor([[2, 1, 0],
        [2, 0, 1]])

In [44]:
sorted_tensor, sorted_indices = torch.sort(initial_tensor, dim = 0)
sorted_tensor

tensor([[0.1871, 0.4887, 0.0179],
        [0.9763, 0.4889, 0.1111]])

In [45]:
sorted_indices

tensor([[1, 1, 1],
        [0, 0, 0]])