In [1]:
#install.packages("NMOF")

In [2]:
library("NMOF")

In [3]:
set.seed(1345797)

In [4]:
N <- 8

In [5]:
rand_position <- sample.int(N)

rand_position

[1] 6 5 7 2 3 8 1 4

In [6]:
data_frame <- data.frame(row = 1:N, column = rand_position)

data_frame

row column
1 1   6     
2 2   5     
3 3   7     
4 4   2     
5 5   3     
6 6   8     
7 7   1     
8 8   4

In [7]:
chessboard <- function(rand_position, queen = "Q", sep = '  ') {
    n <- length(rand_position)
    row <- rep('_', n)

    for (i in seq_len(n)) {
        row_i <- row
        row_i[rand_position[i]] <- queen
        
        cat(paste(row_i, collapse = sep))
        cat('\n')
    }
}

In [8]:
chessboard(rand_position)

_  _  _  _  _  Q  _  _
_  _  _  _  Q  _  _  _
_  _  _  _  _  _  Q  _
_  Q  _  _  _  _  _  _
_  _  Q  _  _  _  _  _
_  _  _  _  _  _  _  Q
Q  _  _  _  _  _  _  _
_  _  _  Q  _  _  _  _


In [9]:
matrix_diag <- array(NA, dim = c(N, N))

matrix_diag

[,1] [,2] [,3] [,4] [,5] [,6] [,7] [,8]
[1,] NA   NA   NA   NA   NA   NA   NA   NA  
[2,] NA   NA   NA   NA   NA   NA   NA   NA  
[3,] NA   NA   NA   NA   NA   NA   NA   NA  
[4,] NA   NA   NA   NA   NA   NA   NA   NA  
[5,] NA   NA   NA   NA   NA   NA   NA   NA  
[6,] NA   NA   NA   NA   NA   NA   NA   NA  
[7,] NA   NA   NA   NA   NA   NA   NA   NA  
[8,] NA   NA   NA   NA   NA   NA   NA   NA

In [10]:
for (row in 1:N)
    for (col in 1:N)
        matrix_diag[row, col] <- col - row

matrix_diag

[,1] [,2] [,3] [,4] [,5] [,6] [,7] [,8]
[1,]  0    1    2    3    4    5    6   7   
[2,] -1    0    1    2    3    4    5   6   
[3,] -2   -1    0    1    2    3    4   5   
[4,] -3   -2   -1    0    1    2    3   4   
[5,] -4   -3   -2   -1    0    1    2   3   
[6,] -5   -4   -3   -2   -1    0    1   2   
[7,] -6   -5   -4   -3   -2   -1    0   1   
[8,] -7   -6   -5   -4   -3   -2   -1   0

In [11]:
for (row in 1:N)
    for (col in 1:N)
        matrix_diag[row, col] <- col + row - (N + 1)

matrix_diag

[,1] [,2] [,3] [,4] [,5] [,6] [,7] [,8]
[1,] -7   -6   -5   -4   -3   -2   -1   0   
[2,] -6   -5   -4   -3   -2   -1    0   1   
[3,] -5   -4   -3   -2   -1    0    1   2   
[4,] -4   -3   -2   -1    0    1    2   3   
[5,] -3   -2   -1    0    1    2    3   4   
[6,] -2   -1    0    1    2    3    4   5   
[7,] -1    0    1    2    3    4    5   6   
[8,]  0    1    2    3    4    5    6   7

In [12]:
rand_position

[1] 6 5 7 2 3 8 1 4

In [13]:
duplicated(rand_position)

[1] FALSE FALSE FALSE FALSE FALSE FALSE FALSE FALSE

In [14]:
sum(duplicated(rand_position))

[1] 0

In [15]:
duplicated(rand_position - seq_along(rand_position))

[1] FALSE FALSE FALSE FALSE  TRUE FALSE FALSE FALSE

In [16]:
rand_position - seq_along(rand_position)

[1]  5  3  4 -2 -2  2 -6 -4

In [17]:
sum(duplicated(rand_position - seq_along(rand_position)))

[1] 1

In [18]:
duplicated(rand_position + seq_along(rand_position))

[1] FALSE  TRUE FALSE FALSE FALSE FALSE  TRUE FALSE

In [19]:
rand_position + seq_along(rand_position)

[1]  7  7 10  6  8 14  8 12

In [20]:
sum(duplicated(rand_position + seq_along(rand_position)))

[1] 2

In [21]:
num_attacks <- function(rand_position) {
    sum(duplicated(rand_position)) + 
    sum(duplicated(rand_position - seq_along(rand_position))) + 
    sum(duplicated(rand_position + seq_along(rand_position)))
}

In [22]:
num_attacks(rand_position)

[1] 3

In [23]:
move_one_queen <- function(rand_position){
    step <- 4
    i <- sample.int(N, 1)
    
    rand_position[i] <- rand_position[i] + sample(c(1:step, -(1:step)), 1)
    
    if (rand_position[i] > N)
        rand_position[i] <- 1
    else if (rand_position[i] < 1)
        rand_position[i] <- N
    
    rand_position
}

In [24]:
chessboard(rand_position)

_  _  _  _  _  Q  _  _
_  _  _  _  Q  _  _  _
_  _  _  _  _  _  Q  _
_  Q  _  _  _  _  _  _
_  _  Q  _  _  _  _  _
_  _  _  _  _  _  _  Q
Q  _  _  _  _  _  _  _
_  _  _  Q  _  _  _  _


In [25]:
chessboard(rand_position <- move_one_queen(rand_position))

_  _  _  _  _  Q  _  _
_  Q  _  _  _  _  _  _
_  _  _  _  _  _  Q  _
_  Q  _  _  _  _  _  _
_  _  Q  _  _  _  _  _
_  _  _  _  _  _  _  Q
Q  _  _  _  _  _  _  _
_  _  _  Q  _  _  _  _


In [26]:
chessboard(rand_position <- move_one_queen(rand_position))

_  _  _  _  _  Q  _  _
_  Q  _  _  _  _  _  _
_  _  _  _  _  _  Q  _
_  Q  _  _  _  _  _  _
_  _  Q  _  _  _  _  _
_  _  _  _  _  _  _  Q
_  Q  _  _  _  _  _  _
_  _  _  Q  _  _  _  _


In [27]:
p0 <- rep(2, N)

p0

[1] 2 2 2 2 2 2 2 2

In [28]:
chessboard(p0)

_  Q  _  _  _  _  _  _
_  Q  _  _  _  _  _  _
_  Q  _  _  _  _  _  _
_  Q  _  _  _  _  _  _
_  Q  _  _  _  _  _  _
_  Q  _  _  _  _  _  _
_  Q  _  _  _  _  _  _
_  Q  _  _  _  _  _  _


In [29]:
chessboard(rand_position <- move_one_queen(p0))

_  Q  _  _  _  _  _  _
_  Q  _  _  _  _  _  _
_  _  _  _  _  Q  _  _
_  Q  _  _  _  _  _  _
_  Q  _  _  _  _  _  _
_  Q  _  _  _  _  _  _
_  Q  _  _  _  _  _  _
_  Q  _  _  _  _  _  _


In [30]:
chessboard(rand_position <- move_one_queen(rand_position))

_  Q  _  _  _  _  _  _
_  Q  _  _  _  _  _  _
_  _  _  _  _  Q  _  _
_  Q  _  _  _  _  _  _
_  Q  _  _  _  _  _  _
_  Q  _  _  _  _  _  _
_  _  _  _  _  _  _  Q
_  Q  _  _  _  _  _  _


In [31]:
stochastic_local_search <- LSopt(num_attacks, list(x0 = p0, neighbour = move_one_queen,
                                 printBar = T, nS = 10000))


Local Search.
Initial solution:  7 
  |======================================================================| 100%
Finished.
Best solution overall: 0


In [32]:
stochastic_local_search$xbest

[1] 3 5 2 8 1 7 4 6

In [33]:
chessboard(stochastic_local_search$xbest)

_  _  Q  _  _  _  _  _
_  _  _  _  Q  _  _  _
_  Q  _  _  _  _  _  _
_  _  _  _  _  _  _  Q
Q  _  _  _  _  _  _  _
_  _  _  _  _  _  Q  _
_  _  _  Q  _  _  _  _
_  _  _  _  _  Q  _  _


In [34]:
num_attacks(stochastic_local_search$xbest)

[1] 0

In [35]:
stochastic_local_search$OFvalue

[1] 0

In [36]:
threshold_accepting_search <- TAopt(num_attacks, list(x0 = p0, neighbour = move_one_queen,
                                    printBar = T, nS = 10000))


Threshold Accepting

  Computing thresholds ... 
  |============================================================| 100%
  OK
  Estimated remaining running time: 53 secs

  Running Threshold Accepting ...
  Initial solution: 7 
  |============================================================| 100%
  Finished.
  Best solution overall: 1


In [37]:
threshold_accepting_search$x0

[1] 2 2 2 2 2 2 2 2

In [38]:
threshold_accepting_search$xbest

[1] 8 6 3 7 4 1 5 2

In [39]:
chessboard(threshold_accepting_search$xbest)

_  _  _  _  _  _  _  Q
_  _  _  _  _  Q  _  _
_  _  Q  _  _  _  _  _
_  _  _  _  _  _  Q  _
_  _  _  Q  _  _  _  _
Q  _  _  _  _  _  _  _
_  _  _  _  Q  _  _  _
_  Q  _  _  _  _  _  _


In [40]:
num_attacks(threshold_accepting_search$xbest)

[1] 1

In [41]:
threshold_accepting_search$OFvalue

[1] 1

In [42]:
simulated_annealing_search <- SAopt(num_attacks, list(x0 = p0, neighbour = move_one_queen,
                                    printBar = T, nS = 10000))


Simulated Annealing.

  |======================================================================| 100%
OK
Estimated remaining running time: 99 secs.

Running Simulated Annealing ...
Initial solution:  7 
  |======================================================================| 100%Finished.
Best solution overall: 0



In [43]:
simulated_annealing_search$xbest

[1] 4 8 5 3 1 7 2 6

In [44]:
chessboard(simulated_annealing_search$xbest)

_  _  _  Q  _  _  _  _
_  _  _  _  _  _  _  Q
_  _  _  _  Q  _  _  _
_  _  Q  _  _  _  _  _
Q  _  _  _  _  _  _  _
_  _  _  _  _  _  Q  _
_  Q  _  _  _  _  _  _
_  _  _  _  _  Q  _  _


In [45]:
num_attacks(simulated_annealing_search$xbest)

[1] 0

In [46]:
simulated_annealing_search$OFvalue

[1] 0