In [1]:
import sklearn

import numpy as np
import pandas as pd

from sklearn.linear_model import LinearRegression
from sklearn.model_selection import KFold, cross_val_score

In [2]:
houseprice_df = pd.read_csv("data/houseprice_data.csv")
houseprice_df.head()

price  bedrooms  bathrooms  sqft_living  sqft_lot  floors  waterfront  \
0  221900.0         3       1.00         1180      5650     1.0           0   
1  538000.0         3       2.25         2570      7242     2.0           0   
2  180000.0         2       1.00          770     10000     1.0           0   
3  604000.0         4       3.00         1960      5000     1.0           0   
4  510000.0         3       2.00         1680      8080     1.0           0   

   view  condition  grade  sqft_above  sqft_basement  yr_built  yr_renovated  \
0     0          3      7      1180.0              0      1955             0   
1     0          3      7      2170.0            400      1951             1   
2     0          3      6       770.0              0      1933             0   
3     0          5      7      1050.0            910      1965             0   
4     0          3      8      1680.0              0      1987             0   

   sqft_living15  sqft_lot15  
0           1340        5650  
1           1690        7639  
2           2720        8062  
3           1360        5000  
4           1800        7503

In [3]:
Y = (np.array(houseprice_df["price"], dtype = "float64")).reshape(-1, 1)

In [4]:
X = houseprice_df.drop("price", axis=1)
X = np.array(X)

In [5]:
X.shape, Y.shape

((21611, 15), (21611, 1))

In [6]:
kf = KFold(n_splits=3)
list(kf.split(X))

[(array([ 7204,  7205,  7206, ..., 21608, 21609, 21610]),
  array([   0,    1,    2, ..., 7201, 7202, 7203])),
 (array([    0,     1,     2, ..., 21608, 21609, 21610]),
  array([ 7204,  7205,  7206, ..., 14405, 14406, 14407])),
 (array([    0,     1,     2, ..., 14405, 14406, 14407]),
  array([14408, 14409, 14410, ..., 21608, 21609, 21610]))]

In [7]:
i = 1

for train, test in kf.split(X):
    print("\nTrain" + str(i), train)
    print("Test" + str(i), test)

    i += 1


Train1 [ 7204  7205  7206 ... 21608 21609 21610]
Test1 [   0    1    2 ... 7201 7202 7203]

Train2 [    0     1     2 ... 21608 21609 21610]
Test2 [ 7204  7205  7206 ... 14405 14406 14407]

Train3 [    0     1     2 ... 14405 14406 14407]
Test3 [14408 14409 14410 ... 21608 21609 21610]


In [8]:
len(X), len(train), len(test)

(21611, 14408, 7203)

In [9]:
kf = KFold(n_splits=4)

i = 1
for train, test in kf.split(X):
    print("\nTrain" + str(i), train)
    print("Test" + str(i), test)

    i += 1


Train1 [ 5403  5404  5405 ... 21608 21609 21610]
Test1 [   0    1    2 ... 5400 5401 5402]

Train2 [    0     1     2 ... 21608 21609 21610]
Test2 [ 5403  5404  5405 ... 10803 10804 10805]

Train3 [    0     1     2 ... 21608 21609 21610]
Test3 [10806 10807 10808 ... 16206 16207 16208]

Train4 [    0     1     2 ... 16206 16207 16208]
Test4 [16209 16210 16211 ... 21608 21609 21610]


In [10]:
len(X), len(train), len(test)

(21611, 16209, 5402)

In [11]:
kf = KFold(n_splits=15)

i = 1
for train, test in kf.split(X):
    print("\nTrain" + str(i), train)
    print("Test" + str(i), test)

    i += 1


Train1 [ 1441  1442  1443 ... 21608 21609 21610]
Test1 [   0    1    2 ... 1438 1439 1440]

Train2 [    0     1     2 ... 21608 21609 21610]
Test2 [1441 1442 1443 ... 2879 2880 2881]

Train3 [    0     1     2 ... 21608 21609 21610]
Test3 [2882 2883 2884 ... 4320 4321 4322]

Train4 [    0     1     2 ... 21608 21609 21610]
Test4 [4323 4324 4325 ... 5761 5762 5763]

Train5 [    0     1     2 ... 21608 21609 21610]
Test5 [5764 5765 5766 ... 7202 7203 7204]

Train6 [    0     1     2 ... 21608 21609 21610]
Test6 [7205 7206 7207 ... 8643 8644 8645]

Train7 [    0     1     2 ... 21608 21609 21610]
Test7 [ 8646  8647  8648 ... 10084 10085 10086]

Train8 [    0     1     2 ... 21608 21609 21610]
Test8 [10087 10088 10089 ... 11525 11526 11527]

Train9 [    0     1     2 ... 21608 21609 21610]
Test9 [11528 11529 11530 ... 12966 12967 12968]

Train10 [    0     1     2 ... 21608 21609 21610]
Test10 [12969 12970 12971 ... 14407 14408 14409]

Train11 [    0     1     2 ... 21608 21609 21610]
Tes

In [12]:
kf = KFold(n_splits=2)

indicies_list = list(kf.split(X))
indicies_list

[(array([10806, 10807, 10808, ..., 21608, 21609, 21610]),
  array([    0,     1,     2, ..., 10803, 10804, 10805])),
 (array([    0,     1,     2, ..., 10803, 10804, 10805]),
  array([10806, 10807, 10808, ..., 21608, 21609, 21610]))]

In [13]:
indicies_list[0]

(array([10806, 10807, 10808, ..., 21608, 21609, 21610]),
 array([    0,     1,     2, ..., 10803, 10804, 10805]))

In [19]:
X_train1, y_train1 = X[indicies_list[0][0]], Y[indicies_list[0][0]]
X_test1, y_test1 = X[indicies_list[0][1]], Y[indicies_list[0][1]]

X_train2, y_train2 = X[indicies_list[1][0]], Y[indicies_list[1][0]]
X_test2, y_test2 = X[indicies_list[1][1]], Y[indicies_list[1][1]]

In [20]:
X_train1.shape, y_train1.shape

((10805, 15), (10805, 1))

In [21]:
X_train2.shape, y_train2.shape

((10806, 15), (10806, 1))

In [22]:
X_test2.shape, y_test2.shape

((10805, 15), (10805, 1))

In [23]:
reg = LinearRegression().fit(X_train1, y_train1)
reg.score(X_test1, y_test1)

0.6455507637942682

In [25]:
reg = LinearRegression().fit(X_train2, y_train2)
reg.score(X_test2, y_test2)

0.644251856944084

In [26]:
cross_val_score(reg, X, Y, cv=2)

array([0.64555076, 0.64425186])