In [1]:
library(NMOF)

In [2]:
board_size <- 8

In [3]:
pos <- sample.int(board_size)
pos

[1] 7 8 3 1 6 4 2 5

In [4]:
data.frame(row =1:board_size, column = pos)

row column
1 1   7     
2 2   8     
3 3   3     
4 4   1     
5 5   6     
6 6   4     
7 7   2     
8 8   5

In [5]:
print_board <- function(position, q.char="1", sep=" ") {
    n <- length(position)
    row <- rep("*", n)

    for (i in seq_len(n)) {
        row_i <- row
        row_i[position[i]] <- q.char

        cat(paste(row_i, collapse = sep))
        cat("\n")
    }
}

In [6]:
print_board(pos)

* * * * * * 1 *
* * * * * * * 1
* * 1 * * * * *
1 * * * * * * *
* * * * * 1 * *
* * * 1 * * * *
* 1 * * * * * *
* * * * 1 * * *


In [7]:
board <- array(NA, dim=c(board_size, board_size))

board

[,1] [,2] [,3] [,4] [,5] [,6] [,7] [,8]
[1,] NA   NA   NA   NA   NA   NA   NA   NA  
[2,] NA   NA   NA   NA   NA   NA   NA   NA  
[3,] NA   NA   NA   NA   NA   NA   NA   NA  
[4,] NA   NA   NA   NA   NA   NA   NA   NA  
[5,] NA   NA   NA   NA   NA   NA   NA   NA  
[6,] NA   NA   NA   NA   NA   NA   NA   NA  
[7,] NA   NA   NA   NA   NA   NA   NA   NA  
[8,] NA   NA   NA   NA   NA   NA   NA   NA

In [8]:
for (row in 1:board_size)
    for (col in 1:board_size)
        board[row, col] <- col - row

board

[,1] [,2] [,3] [,4] [,5] [,6] [,7] [,8]
[1,]  0    1    2    3    4    5    6   7   
[2,] -1    0    1    2    3    4    5   6   
[3,] -2   -1    0    1    2    3    4   5   
[4,] -3   -2   -1    0    1    2    3   4   
[5,] -4   -3   -2   -1    0    1    2   3   
[6,] -5   -4   -3   -2   -1    0    1   2   
[7,] -6   -5   -4   -3   -2   -1    0   1   
[8,] -7   -6   -5   -4   -3   -2   -1   0

In [9]:
board <- array(NA, dim=c(board_size, board_size))

for (row in 1:board_size)
    for (col in 1:board_size)

        board[row, col] <- col + row - (board_size + 1)

board

[,1] [,2] [,3] [,4] [,5] [,6] [,7] [,8]
[1,] -7   -6   -5   -4   -3   -2   -1   0   
[2,] -6   -5   -4   -3   -2   -1    0   1   
[3,] -5   -4   -3   -2   -1    0    1   2   
[4,] -4   -3   -2   -1    0    1    2   3   
[5,] -3   -2   -1    0    1    2    3   4   
[6,] -2   -1    0    1    2    3    4   5   
[7,] -1    0    1    2    3    4    5   6   
[8,]  0    1    2    3    4    5    6   7

In [10]:
pos

[1] 7 8 3 1 6 4 2 5

In [11]:
duplicated(pos)

[1] FALSE FALSE FALSE FALSE FALSE FALSE FALSE FALSE

In [12]:
seq_along(pos)

[1] 1 2 3 4 5 6 7 8

In [13]:
pos - seq_along(pos)

[1]  6  6  0 -3  1 -2 -5 -3

In [14]:
duplicated(pos - seq_along(pos))

[1] FALSE  TRUE FALSE FALSE FALSE FALSE FALSE  TRUE

In [15]:
sum(duplicated(pos - seq_along(pos)))

[1] 2

In [16]:
sum(duplicated(pos + seq_along(pos)))

[1] 1

In [17]:
n_attacks <- function(position) {
    sum(duplicated(position)) +
    sum(duplicated(position - seq_along(position))) +
    sum(duplicated(position + seq_along(position)))
}

In [18]:
n_attacks(pos)

[1] 3

In [19]:
neighbor <- function(position) {
    step <- 2
    i <- sample.int(board_size, 1)

    position[i] <- position[i] + sample(c(1:step, -(1:step)), 1)

    if (position[i] > board_size)
        position[i] <- 1
    else if (position[i] < 1)
        position[i] <- board_size
    
    position
}

In [20]:
print_board(pos)

* * * * * * 1 *
* * * * * * * 1
* * 1 * * * * *
1 * * * * * * *
* * * * * 1 * *
* * * 1 * * * *
* 1 * * * * * *
* * * * 1 * * *


In [21]:
print_board(pos <- neighbor(pos))

* * * * * * 1 *
* * * * * * * 1
* * 1 * * * * *
1 * * * * * * *
* * * * * 1 * *
* * * 1 * * * *
* 1 * * * * * *
* * * 1 * * * *


In [22]:
pos0 <- rep(1, board_size)

In [23]:
print_board(pos0)

1 * * * * * * *
1 * * * * * * *
1 * * * * * * *
1 * * * * * * *
1 * * * * * * *
1 * * * * * * *
1 * * * * * * *
1 * * * * * * *


In [24]:
solution <- SAopt(n_attacks, list(x0 = pos0,
                                  neighbour = neighbor,
                                  printBar = TRUE,
                                  nS = 1000))


Simulated Annealing.

  |======================================================================| 100%
OK
Estimated remaining running time: 2.5 secs.

Running Simulated Annealing ...
Initial solution:  7 
  |======================================================================| 100%Finished.
Best solution overall: 0



In [25]:
solution$xbest

[1] 3 6 4 1 8 5 7 2

In [26]:
n_attacks(solution$xbest)

[1] 0

In [27]:
print_board(solution$xbest)

* * 1 * * * * *
* * * * * 1 * *
* * * 1 * * * *
1 * * * * * * *
* * * * * * * 1
* * * * 1 * * *
* * * * * * 1 *
* 1 * * * * * *


In [28]:
solution <- LSopt(n_attacks, list(x0 = pos0,
                                neighbour= neighbor,
                                printBar = TRUE,
                                nS = 1000))


Local Search.
Initial solution:  7 
  |======================================================================| 100%
Finished.
Best solution overall: 1


In [29]:
n_attacks(solution$xbest)

[1] 1

In [30]:
print_board(solution$xbest)

* * * * * * 1 *
* 1 * * * * * *
* * * * * 1 * *
* * 1 * * * * *
1 * * * * * * *
* * * * * * * 1
* * * * 1 * * *
* * 1 * * * * *


In [31]:
solution <- TAopt(n_attacks, list(x0 = pos0,
neighbour = neighbor,
printBar = TRUE,
nS = 1000))


Threshold Accepting

  Computing thresholds ... 
  |============================================================| 100%
  OK
  Estimated remaining running time: 2.05 secs

  Running Threshold Accepting ...
  Initial solution: 7 
  |============================================================| 100%
  Finished.
  Best solution overall: 1


In [32]:
n_attacks(solution$xbest)

[1] 1

In [33]:
print_board(solution$xbest)

* * * * * * 1 *
* * * * 1 * * *
* 1 * * * * * *
* * * * * 1 * *
1 * * * * * * *
* * 1 * * * * *
* * * * * * * 1
* * 1 * * * * *


In [34]:
pos0 <- sample.int(board_size)

In [35]:
print_board(pos0)

* * * * * * * 1
1 * * * * * * *
* * * * * * 1 *
* * * * * 1 * *
* 1 * * * * * *
* * * * 1 * * *
* * * 1 * * * *
* * 1 * * * * *


In [36]:
solution <- SAopt(n_attacks, list(x0 = pos0,
neighbour = neighbor,
printBar = TRUE,
nS=1000))


Simulated Annealing.

  |======================================================================| 100%
OK
Estimated remaining running time: 2.85 secs.

Running Simulated Annealing ...
Initial solution:  5 
  |======================================================================| 100%Finished.
Best solution overall: 0



In [37]:
n_attacks(solution$xbest)

[1] 0

In [38]:
print_board(solution$xbest)

* * * * 1 * * *
1 * * * * * * *
* * * 1 * * * *
* * * * * 1 * *
* * * * * * * 1
* 1 * * * * * *
* * * * * * 1 *
* * 1 * * * * *


In [39]:
solution <- LSopt(n_attacks, list(x0 = pos0,
neighbour =neighbor,
printBar =TRUE,
nS = 1000 ))


Local Search.
Initial solution:  5 
  |======================================================================| 100%
Finished.
Best solution overall: 0


In [40]:
n_attacks(solution$xbest)

[1] 0

In [41]:
print_board(solution$xbest)

* * * * * * * 1
* * 1 * * * * *
1 * * * * * * *
* * * * * 1 * *
* 1 * * * * * *
* * * * 1 * * *
* * * * * * 1 *
* * * 1 * * * *


In [42]:
solution <- TAopt(n_attacks, list(x0 = pos0,
neighbour = neighbor, printBar = TRUE, nS = 1000))


Threshold Accepting

  Computing thresholds ... 
  |============================================================| 100%
  OK
  Estimated remaining running time: 2.2 secs

  Running Threshold Accepting ...
  Initial solution: 5 
  |============================================================| 100%
  Finished.
  Best solution overall: 0


In [43]:
n_attacks(solution$xbest)

[1] 0

In [44]:
print_board(solution$xbest)

* * * * 1 * * *
* * * * * * * 1
* * * 1 * * * *
1 * * * * * * *
* * 1 * * * * *
* * * * * 1 * *
* 1 * * * * * *
* * * * * * 1 *
